### ISSUE TITLE
Implement UI to select a region of an image

### ISSUE THREAD

**Issue by pkasila** [StudyForces/sources-ui#1]
## What is needed?

We need a UI to select a region of the image to be proceeded by OCR.

## Format of the data

At this moment a region is considered to be a rectangle region defined by this structure:
```json
{
   "x": 0,
   "y": 0,
   "width": 1024,
   "height": 512,
}
```

In the future, it may be defined different ways, but the possible one is:
```json
{
   "polygin": [
      {"x": 0, "y": 0},
      {"x": 512, "y": 0},
      {"x": 512, "y": 1024},
      {"x": 0, "y": 1024},
   ]
}
```

So, it should be possible to easily switch to such a representation of a region.

**Comment by Kononenko-Daniil** [comment]
Ок
